name: Deploy to Staging

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  AZURE_WEBAPP_NAME: your-project-tracker-frontend-staging # Replace with your staging Azure Web App name
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_ENV: staging

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Build application
      run: npm run build
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure Staging
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        startup-command: 'npm start'
        app-settings: |
          NODE_ENV=staging
          NEXT_PUBLIC_API_URL=https://project-tracker-backend-xi.vercel.app
        
    - name: Run smoke tests
      run: |
        # Add your smoke test commands here
        echo "Running smoke tests..."
        # curl -f https://your-staging-app.azurewebsites.net/health || exit 1
        
    - name: Azure logout
      run: |
        az logout
